logger:
  level: DEBUG
  output_file: logs/logs.log

parser:
  base_url: "https://api.example.com/v1"
  endpoints:
    - "/listings"
    - "/details"

scrapper:
  base_url: "https://www.example.com"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"
