logger:
  level: ERROR
  output_file: logs/logs.log

parser:
  yandex_geocode_url: "https://geocode-maps.yandex.ru/v1"
  yandex_routing_url: "https://api.routing.yandex.net/v2"
  overpass_url: "https://overpass-api.de/api"
  aqicn_url: "https://api.waqi.info"
  dadata_url: "https://suggestions.dadata.ru/suggestions/api/4_1"

scrapper:
  base_url: "https://www.example.com"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"
  domain: "https://domclick.ru"

excel:
  raw_path: "data/raw/data1.xlsx"
  temp_path: "data/temp/data.xlsx"
  processed_path: "data/processed/data.xlsx"
  raw_sheet_name: "Sheet1"
  temp_sheet_name: "Sheet1"
  processed_sheet_name: "Sheet1"